### ISSUE TITLE
Tests for all sub-packages

### ISSUE THREAD

**Issue by GMartigny** [GMartigny/pencil.js#3]
All packages should have their own tests.

 - [x] Arc
 - [x] BaseEvent
 - [x] Button
 - [x] Checkbox
 - [x] Circle
 - [x] Component
 - [x] Container
 - [ ] draggable()
 - [x] EventEmitter
 - [x] Image
 - [ ] Input
 - [x] KeyboardEvent
 - [x] Line
 - [x] Math
 - [x] MouseEvent
 - [x] NetworkEvent
 - [x] OffscreenCanvas
 - [ ] Path
 - [x] Polygon
 - [x] Position
 - [x] Rectangle
 - [x] RegularPolygon
 - [ ] resizable()
 - [ ] Scene
 - [x] Select
 - [ ] Slider
 - [x] Spline
 - [x] Square
 - [x] Star
 - [x] Text
 - [x] Triangle
 - [x] Vector

**Comment by Euklidian-Space** [comment]
Hey @GMartigny, I am interested in contributing to this issue.  However, when I fork/clone the project and try to run npm install I get get 404 not found on all of the scoped packages.  Have you published them?

**Comment by GMartigny** [comment]
Hi @Euklidian-Space ,
Glad to have someone interested. All packages are to be published (the "pencil.js" name is taken for now). So to handle this situtation, I use [lerna](lernajs.io) to link all packages together.
Run on the project root directory : 
```
npm install -g lerna
lerna bootstrap
```
Tell me is this is ok then ;)

**Comment by Euklidian-Space** [comment]
@GMartign, those steps worked!  Going to get started.

**Comment by Euklidian-Space** [comment]
Hey @GMartigny , I think having a mock for a context2D object would help speed up the testing process.  Have you seen this project https://github.com/hustcc/jest-canvas-mock, we might want it as a dev dependency.  What do you think?

**Comment by GMartigny** [comment]
Yeah looks good to me. It's sometimes nice to [count number of calls to a mocked function](https://github.com/GMartigny/pencil.js/blob/master/modules/spline/spline.test.js#L19).
But looks like it can be done with this package.

Try it, and if it helps you, adds it as devDep in your PR.

**Comment by GMartigny** [comment]
In order to check overall code coverage, go to [CodeClimate report](https://codeclimate.com/github/GMartigny/pencil.js/code).
